### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by xt99** [cloudscaling/puppet-scaleio#1]
Hi guys!

Do you have any plans to include support for CentOS 7 (not only Ubuntu 14.04) in this Puppet module for ScaleIO 2.x?
 
Seems like overall situation with CentOS 7 support for ScaleIO in Puppet is not the best one. [Official Puppet module for ScaleIO 1.3](https://github.com/emccode/puppet-scaleio) supports only CentOS 6 (previous upstream version). This Puppet module for ScaleIO 2.x supports only Ubuntu 14.04. So having CentOS 7 as a first class citizen in one's infrastructure making it impossible to use ScaleIO with Puppet.

**Comment by Andrey-mp** [comment]
Hi,
Yes, we have such plans. And Tim Rozet is working in this area - https://github.com/cloudscaling/puppet-scaleio/commit/34b99b70acbdb97eb37f7ceb4fbb9794414d0391

But right now we should release our first version and supporting of CentOS/RedHat will be in the next version.

**Comment by xt99** [comment]
Ok, thanks for sharing that!

Let me take a look at your CentOS 7 implementation at 34b99b7 and play with it for a while.

**Comment by xt99** [comment]
Sorry, unable to test due to #2

**Comment by Andrey-mp** [comment]
fixed in official repository https://github.com/emccode/puppet-scaleio
