### ISSUE TITLE
Puppet 4 support

### ISSUE THREAD

**Issue by xt99** [cloudscaling/puppet-scaleio#2]
Seems like this module is completely broken when used with Puppet 4 (`4.3.2` in my case).

**Comment by Andrey-mp** [comment]
Hi,
How did you install puppet 4?
We've tried to install it with yum and taken 3.6.3
Maximum version for ubuntu is 3.8
puppetlabs has 3.8 too.
Puppet 4 is only available via ruby install but this is not production way.

**Comment by xt99** [comment]
I have a Vagrant with official PuppetLabs box [`puppetlabs/centos-7.2-64-puppet`](https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.2-64-puppet) where Puppet `4.3.2` is preinstalled.

**Comment by Andrey-mp** [comment]
Could you provide exact error? 
I've tried puppet 4.5.2 and if it was installed correctly - code works.

**Comment by Andrey-mp** [comment]
all issues were fixed in official repository - https://github.com/emccode/puppet-scaleio
